In [3]:
import numpy as np
a = [1,2,3,4]
print(np.array(a))

[1 2 3 4]


In [4]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
