Tensors in PyTorch

In [1]:
import torch

tensor_1d = torch.tensor([1, 2, 3])
print("1D Tensor (Vector):")
print(tensor_1d)
print()

1D Tensor (Vector):
tensor([1, 2, 3])



In [2]:
tensor_2d = torch.tensor([[1, 2], [3, 4]])
print("2D Tensor (Matrix):")
print(tensor_2d)
print()

2D Tensor (Matrix):
tensor([[1, 2],
        [3, 4]])



In [ ]:
random_tensor = torch.rand(2, 3)
print("Random Tensor (2x3):")
print(random_tensor)
print()

In [ ]:
zeros_tensor = torch.zeros(2, 3)
print("Zeros Tensor (2x3):")
print(zeros_tensor)
print()

In [ ]:
ones_tensor = torch.ones(2, 3)
print("Ones Tensor (2x3):")
print(ones_tensor)

Indexing and Slicing

In [ ]:
import torch

tensor = torch.tensor([[1, 2], [3, 4], [5, 6]])

element = tensor[1, 0]
print(f"Indexed Element (Row 1, Column 0): {element}")  
slice_tensor = tensor[:2, :]
print(f"Sliced Tensor (First two rows): \n{slice_tensor}")

reshaped_tensor = tensor.view(2, 3)
print(f"Reshaped Tensor (2x3): \n{reshaped_tensor}")

In [19]:
tensor = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(tensor)
element = tensor[0,2]
print(element)
slice_tensor = tensor[1:2,0:2]
print(slice_tensor)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor(3)
tensor([[4, 5]])


In [46]:
slicing = tensor[0:,1:3]
print(slicing)

tensor([[2, 3],
        [5, 6],
        [8, 9]])


Common Tensor Functions: Broadcasting, Matrix Multiplication, etc.

In [20]:
import torch

tensor_a = torch.tensor([[1, 2, 3], [4, 5, 6]])

tensor_b = torch.tensor([[10, 20, 30]]) 

broadcasted_result = tensor_a + tensor_b 
print(f"Broadcasted Addition Result: \n{broadcasted_result}")

matrix_multiplication_result = torch.matmul(tensor_a, tensor_a.T)
print(f"Matrix Multiplication Result (tensor_a * tensor_a^T): \n{matrix_multiplication_result}")

Broadcasted Addition Result: 
tensor([[11, 22, 33],
        [14, 25, 36]])
Matrix Multiplication Result (tensor_a * tensor_a^T): 
tensor([[14, 32],
        [32, 77]])


GPU Acceleration with PyTorch

In [21]:
import torch

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'Using device: {device}')

tensor_size = (10000, 10000)  
a = torch.randn(tensor_size, device=device)  
b = torch.randn(tensor_size, device=device)  

c = a + b  

print("Result shape (moved to CPU for printing):", c.cpu().shape)

print("Current GPU memory usage:")
print(f"Allocated: {torch.cuda.memory_allocated(device) / (1024 ** 2):.2f} MB")
print(f"Cached: {torch.cuda.memory_reserved(device) / (1024 ** 2):.2f} MB")

Using device: cpu
Result shape (moved to CPU for printing): torch.Size([10000, 10000])
Current GPU memory usage:
Allocated: 0.00 MB
Cached: 0.00 MB


Building and Training Neural Networks with PyTorch

Step 1: Define the Neural Network Class

In [22]:
import torch
import torch.nn as nn

class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(2, 4)  
        self.fc2 = nn.Linear(4, 1)  

    def forward(self, x):
        x = torch.relu(self.fc1(x))  
        x = self.fc2(x)               
        return x

Step 2: Prepare the Data

In [23]:
X_train = torch.tensor([[0.0, 0.0], [0.0, 1.0], [1.0, 0.0], [1.0, 1.0]]) 
y_train = torch.tensor([[0.0], [1.0], [1.0], [0.0]])

Step 3: Instantiate the Model, Loss Function, and Optimizer

In [38]:
import torch.optim as optim
model = SimpleNN()
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.1)

Step 4: Forward Pass & Loss Calculation Concept

In [39]:
outputs = model(X_train)
loss = criterion(outputs, y_train)

Step 5: Training the Model

In [40]:
for epoch in range(100):
    model.train()

    outputs = model(X_train)
    loss = criterion(outputs, y_train)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if (epoch + 1) % 10 == 0:
        print(f'Epoch [{epoch + 1}/100], Loss: {loss.item():.4f}')

Epoch [10/100], Loss: 0.2661
Epoch [20/100], Loss: 0.2491
Epoch [30/100], Loss: 0.2383
Epoch [40/100], Loss: 0.2282
Epoch [50/100], Loss: 0.2171
Epoch [60/100], Loss: 0.2054
Epoch [70/100], Loss: 0.1935
Epoch [80/100], Loss: 0.1851
Epoch [90/100], Loss: 0.1789
Epoch [100/100], Loss: 0.1743


Step 6: Testing the Model

In [27]:
model.eval()
with torch.no_grad():
    test_data = torch.tensor([[0.0, 0.0], [0.0, 1.0], [1.0, 0.0], [1.0, 1.0]])
    predictions = model(test_data)
    print(f'Predictions:\n{predictions}')

Predictions:
tensor([[0.2179],
        [0.9406],
        [0.8030],
        [0.1059]])


Optimizing Model Training with PyTorch Datasets
1. Efficient Data Handling with Datasets and DataLoaders

In [28]:
import torch
from torch.utils.data import Dataset, DataLoader

class MyDataset(Dataset):
    def __init__(self):
        self.data = torch.tensor([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])
        self.labels = torch.tensor([0, 1, 0])

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        return self.data[idx], self.labels[idx]

dataset = MyDataset()
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

for batch in dataloader:
    print("Batch Data:", batch[0])  
    print("Batch Labels:", batch[1])

Batch Data: tensor([[5., 6.],
        [1., 2.]])
Batch Labels: tensor([0, 0])
Batch Data: tensor([[3., 4.]])
Batch Labels: tensor([1])


2. Enhancing Data Diversity through Augmentation


In [30]:
# import torchvision.transforms as transforms
# from PIL import Image


# image = Image.open('example.jpg')  # Replace 'example.jpg' with your image file

# transform = transforms.Compose([
#     transforms.RandomHorizontalFlip(),
#     transforms.ToTensor()
# ])

# augmented_image = transform(image)
# print("Augmented Image Shape:", augmented_image.shape)

3. Batch Processing for Efficient Training


In [31]:
for epoch in range(2):  
    for inputs, labels in dataloader:
        
        outputs = inputs + 1  
        print(f"Epoch {epoch + 1}, Inputs: {inputs}, Labels: {labels}, Outputs: {outputs}")

Epoch 1, Inputs: tensor([[1., 2.],
        [5., 6.]]), Labels: tensor([0, 0]), Outputs: tensor([[2., 3.],
        [6., 7.]])
Epoch 1, Inputs: tensor([[3., 4.]]), Labels: tensor([1]), Outputs: tensor([[4., 5.]])
Epoch 2, Inputs: tensor([[1., 2.],
        [3., 4.]]), Labels: tensor([0, 1]), Outputs: tensor([[2., 3.],
        [4., 5.]])
Epoch 2, Inputs: tensor([[5., 6.]]), Labels: tensor([0]), Outputs: tensor([[6., 7.]])


Defining kernels,etc

Formula of convolution:

    Output=(Input∗Kernel)+Bias

Output Size Formula
    Output= [(W−F+2P)+1]/S

Models

In [61]:
import numpy as np
import torch

# Define the filter
kernel = torch.tensor(
    [[0, -1, 0],
     [-1, 5, -1], 
     [0, -1, 0]], dtype=torch.float32)

# Define the bias
bias = torch.tensor([5], dtype=torch.float32)

# Define the input image
image = torch.tensor(
    [[1, 2, 3, 4], 
     [5, 6, 7, 8], 
     [9, 10, 11, 12],
     [13, 14, 15, 16]], dtype=torch.float32)

def Output_shape(image, kernel, padding, stride):
    h,w = image.shape[-2],image.shape[-1]
    k_h, k_w = kernel.shape[-2],kernel.shape[-1]

    h_out = (h-k_h-2*padding)//stride[0] +1
    w_out = (w-k_w-2*padding)//stride[1] +1
    return h_out,w_out

Output_shape(image, kernel, padding=0, stride=(1,1))

(2, 2)

In [62]:
output_shape = Output_shape(image, kernel, padding=0, stride=(1,1))
output = np.zeros(output_shape)

for i in range(output_shape[0]):
    for j in range(output_shape[1]):
        output[i,j]=torch.tensordot(image[i:3+i,j:3+j],kernel).numpy() +bias.numpy()
        
output

/tmp/ipykernel_340/1959193081.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  output[i,j]=torch.tensordot(image[i:3+i,j:3+j],kernel).numpy() +bias.numpy()


array([[11., 12.],
       [15., 16.]])

In [54]:
import torchvision.models as models

print(dir(models))

['AlexNet', 'AlexNet_Weights', 'ConvNeXt', 'ConvNeXt_Base_Weights', 'ConvNeXt_Large_Weights', 'ConvNeXt_Small_Weights', 'ConvNeXt_Tiny_Weights', 'DenseNet', 'DenseNet121_Weights', 'DenseNet161_Weights', 'DenseNet169_Weights', 'DenseNet201_Weights', 'EfficientNet', 'EfficientNet_B0_Weights', 'EfficientNet_B1_Weights', 'EfficientNet_B2_Weights', 'EfficientNet_B3_Weights', 'EfficientNet_B4_Weights', 'EfficientNet_B5_Weights', 'EfficientNet_B6_Weights', 'EfficientNet_B7_Weights', 'EfficientNet_V2_L_Weights', 'EfficientNet_V2_M_Weights', 'EfficientNet_V2_S_Weights', 'GoogLeNet', 'GoogLeNetOutputs', 'GoogLeNet_Weights', 'Inception3', 'InceptionOutputs', 'Inception_V3_Weights', 'MNASNet', 'MNASNet0_5_Weights', 'MNASNet0_75_Weights', 'MNASNet1_0_Weights', 'MNASNet1_3_Weights', 'MaxVit', 'MaxVit_T_Weights', 'MobileNetV2', 'MobileNetV3', 'MobileNet_V2_Weights', 'MobileNet_V3_Large_Weights', 'MobileNet_V3_Small_Weights', 'RegNet', 'RegNet_X_16GF_Weights', 'RegNet_X_1_6GF_Weights', 'RegNet_X_32GF_

Example 1

In [63]:
import torch
import torch.nn as nn
import torch.nn.functional as F

# Define the filter
kernel = torch.tensor(
    [[0, -1, 0],
     [-1, 5, -1], 
     [0, -1, 0]], dtype=torch.float32)
kernel = kernel.reshape(1, 1, 3, 3)

# Define the bias
bias = torch.tensor([5], dtype=torch.float32)

# Define the input image
image = torch.tensor(
    [[1, 2, 3, 4], 
     [5, 6, 7, 8], 
     [9, 10, 11, 12],
     [13, 14, 15, 16]], dtype=torch.float32)
image = image.reshape(1, 1, 4, 4)

# Define the convolution operation
conv = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3, bias=False)

# Set the filter for the convolution operation
conv.weight = nn.Parameter(kernel)
conv.bias = nn.Parameter(bias)
# Apply the convolution operation
output = conv(image)

# Print the output
print('Output Shape :',output.shape)
print('Output \n',output)

Output Shape : torch.Size([1, 1, 2, 2])
Output 
 tensor([[[[11., 12.],
          [15., 16.]]]], grad_fn=<ConvolutionBackward0>)


Example 2

In [67]:
import torch
import torch.nn as nn
import torchvision.transforms as T
from PIL import Image

# Read the image file
image = Image.open('B:/AI Engineer Intern/PyTorch 10-03-2026/images_OeP3XHp.png')
  
# convert input image to torch tensor
Input = T.ToTensor()(image)
  
# unsqueeze image to make 4D
Input = Input.unsqueeze(0)
print('Input Tensor :',Input.shape)


# Define the convolution operation
conv = nn.Conv2d(in_channels=3, out_channels=3, kernel_size=3,stride=2, bias=True)

output = conv(Input)

print('Output Tensor :',output.shape)
# squeeze image
Out_img = output.squeeze(0)

# convert tensor to image
Out_img = T.ToPILImage()(Out_img)
Out_img

FileNotFoundError: [Errno 2] No such file or directory: 'B:/AI Engineer Intern/PyTorch 10-03-2026/images_OeP3XHp.png'